### ISSUE TITLE
Mineshaft generation

### ISSUE THREAD

**Issue by xrtxn** [Quidvio/Floating-Islands-1.19#12]
Hey, is it possible to make mineshafts only spawn if it's close enough to the terrain above for chains to spawn? Or disabling it completely?

**Comment by klinbee** [comment]
You can disable the Mineshafts yes, but I may be able to get the chains to form (I had a similar issue in an unrelated data pack). If it works, I'll let you know.

**Comment by klinbee** [comment]
I tried it out, the method did not work here. I can still disable them though if you want.

**Comment by xrtxn** [comment]
Yeah on option to disable them would be great

**Comment by xrtxn** [comment]
This works for me: https://github.com/ISamAtlas/no-mineshafts
