### ISSUE TITLE
Bulky spaced out floating islands

### ISSUE THREAD

**Issue by jamesol1** [Quidvio/Floating-Islands-1.19#13]
Hi sorry for the edit, i found the old custom floating island datapacks, noticed the bulky spaced out floating islands pack didnt seem to work/register? Was wondering if you'd be able to make a bulky island land mass version with more air space between the slands aswell. Revamped versions are very cool but i'd love to use for a world with airships and the land i feel for that is all quite close together and easy to navigate across. I'd personally be using 1.20

Thanks

**Comment by klinbee** [comment]
I'm going to be releasing a data pack soon that will be better, a lot more spaced out, completely unique island generation.
