### ISSUE TITLE
V1.3.1 Incompatible version with 1.19-1.19.3 on Curseforge / Minecraft Installations

### ISSUE THREAD

**Issue by Jesevender** [Quidvio/Floating-Islands-1.19#5]
I get the message: "Made for an older version" in 1.19.3 and "Made for a newer version" in 1.19.2. What version should it be compatible with?

**Comment by klinbee** [comment]
That's really strange, could you send me more details on Discord (Quidvio#4760), like screenshots, etc. I think it's some kind of CurseForge issue, but I don't know why it wouldn't be letting you use it with that..
