### ISSUE TITLE
Not showing as available

### ISSUE THREAD

**Issue by linx80** [Quidvio/Floating-Islands-1.19#6]
This datapack doesn't show as available when loading it. I confirmed that it's copied to the correct folder after selecting it, but it doesn't show as all.
Is this datapack compatible with Minecraft 1.19.2?

**Comment by klinbee** [comment]
It absolutely is, did you unzip the folder first? You may need to do that.

**Comment by linx80** [comment]
Unzip it? Where?

**Comment by klinbee** [comment]
When you download the datapack, it should be in a zipped folder, correct? You need to either unzip the zipped folder or you can copy the "Floating Islands v1.X" folder inside and insert it into the Datapack folder on the create new world screen.

**Comment by linx80** [comment]
Yes, I did that. I tried both. It doesn't work at all. I even tried to manually load it with /datapack load and all I get is a normal created world.

**Comment by klinbee** [comment]
Do you mind sending screenshots of your issue?

**Comment by linx80** [comment]
Hold on! I managed to get it to work now! I saved the world and then I re-created the world in Minecraft. Now it works!
But the problem when loading the datapack, that it doesn't show after it is validated still continues. I have to manually load it with /datapack load, then save the world and then re-create it.
So, maybe that can be in the tutorial it anyone else get this issue?

**Comment by klinbee** [comment]
Yeah I realized like maybe a month after I made that video that installing the Datapack wasn't the clearest. Part of that was skipping a step, and part of it was me assuming that the general public was more familiar with datapacks. I may make an updated tutorial and have it unlisted and linked to help. Glad you got it to work.
