### ISSUE TITLE
About Villages

### ISSUE THREAD

**Issue by Fituu** [Quidvio/Floating-Islands-1.19#7]
Hi, I wanted to ask you if it's possible to change the height villages spawn at, because some villages look really bad when they spawn in the void, and all the villagers instantly die because the village houses don't have floors lol
![2023-06-10_16 16 10](https://github.com/Quidvio/Quidvios-Floating-Islands-Datapack/assets/76887607/36202fe1-e926-4c2b-82db-884d47bfbd9a)
![2023-06-10_16 16 18](https://github.com/Quidvio/Quidvios-Floating-Islands-Datapack/assets/76887607/72b14f09-2d87-4116-b446-1c1c033e2934)

**Comment by klinbee** [comment]
Unfortunately from my previous research, this can only be done using a mod. I have tried thinking of ways to fix this issue in the past, but I do not know what to do tbh.
