### ISSUE TITLE
datapack without oceans

### ISSUE THREAD

**Issue by PeterEnises** [Quidvio/Floating-Islands-1.19#8]
could there be a way of creating a datapack fully without oceans? what should be done in order to do so?
I am asking this because the oceans are huge and bulky in terms of floating islands, so i am wondering if there could be a way of turning of the generation of all oceans

**Comment by PeterEnises** [comment]
also ocean monuments should be disabled, because they generate very high, and covered in water

**Comment by klinbee** [comment]
The reason I added monuments and oceans is to be able to complete all of the advancements in a floating islands world. Getting rid of any of the structures and some of the biomes is fortunately trivial. I can remove the oceans entirely if you'd like me to.

**Comment by PeterEnises** [comment]
if you could do something like 1.5 but without oceans - it would be amazing!
